name: download_data
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - ipython=7.16.3
  - jupyterlab=4.1.3
  - notebook=7.1.3
  - pandas=1.5.3
  - scikit-learn=1.1.3
  - matplotlib=3.5.3
  - seaborn=0.12.2
  - pip=23.3.1
  - pip:
      - ydata-profiling==4.10.0
      - wandb==0.16.6